version: "2"
services:
  aria2:
    image: bernylinville/qbittorrentee
    container_name: qbittorrentee
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/docker/Docker-qBittorrent-Enhanced-Edition/config:/config
      - /mnt/user/downloads:/downloads
    ports:
      - 16004:16004
      - 16004:16004/udp
      - 16003:16003
    restart: unless-stopped
